import { Controller, Post, Body, UseGuards, Req } from '@nestjs/common';
import RegisterRequestDto from './dto/register.request.dto';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { RegisterCommand } from '@api/auth/dto/register.command';
import { AuthInteractor } from '@api/auth/auth.interactor';
import { LoginRequestDto } from './dto/login.request.dto';
import { LoginResponseDto } from './dto/login.response.dto';
import { AuthGuard } from '../../common/auth/guards/auth.guard';

@Controller('auth')
export class AuthController {
  constructor(private readonly authService: AuthInteractor) {}

  @ApiOperation({ summary: 'Register new user. Availability: A.' })
  @ApiTags('user')
  @Post('register')
  async register(@Body() registerRequest: RegisterRequestDto) {
    const registerCommand = new RegisterCommand(registerRequest.email);
    await this.authService.register(registerCommand);
  }

  @ApiOperation({ summary: 'Replace temporary password.' })
  @ApiTags('user')
  @Post('password')
  async replaceTemporaryPassword(
    @Body() replaceRequest: LoginRequestDto,
  ): Promise<LoginResponseDto> {
    return await this.authService.replaceTemporaryPassword(replaceRequest);
  }

  @ApiOperation({ summary: 'Login user.' })
  @ApiTags('user')
  @Post('login')
  async login(
    @Body() loginRequest: LoginRequestDto,
  ): Promise<LoginResponseDto> {
    return await this.authService.login(loginRequest);
  }

  @ApiOperation({ summary: 'Logout user. Signs out from all devices.' })
  @ApiTags('user')
  @ApiBearerAuth()
  @UseGuards(AuthGuard)
  @Post('logout/all')
  async globalLogout(@Req() request): Promise<void> {
    const accessToken = request.headers.authorization.split(' ')[1];
    await this.authService.logout(accessToken);
  }

  @ApiOperation({
    summary:
      'Revokes all of the access tokens generated by, and at the same time as, the specified refresh token.',
  })
  @ApiTags('user')
  @ApiBearerAuth()
  @UseGuards(AuthGuard)
  @Post('logout')
  async logout(@Body() refreshToken: string): Promise<void> {
    await this.authService.revokeRefreshToken(refreshToken);
  }

  @ApiOperation({
    summary:
      'Represents the request to reset a user password as an administrator and to set the new user password..',
  })
  @ApiTags('user')
  @ApiBearerAuth()
  @UseGuards(AuthGuard)
  @Post('/reset/password')
  async resetPassword(
    @Body('email') email: string,
    @Body('newPassword') newPassword: string,
  ): Promise<void> {
    await this.authService.resetPassword(email, newPassword);
  }

  @ApiOperation({
    summary:
      'Represents a request to send to the end user email address a confirmation code required to change the password.',
  })
  @ApiTags('user')
  @Post('/forgot/password')
  async forgotPassword(@Body('email') email: string): Promise<void> {
    await this.authService.initiateForgotPassword(email);
  }

  @ApiOperation({
    summary: 'The request representing the confirmation for a password reset.',
  })
  @ApiTags('user')
  @Post('confirm/password')
  async confirmForgotPassword(
    @Body('email') email: string,
    @Body('newPassword') newPassword: string,
    @Body('confirmationCode') confirmationCode,
  ): Promise<void> {
    await this.authService.confirmForgotPassword(
      email,
      newPassword,
      confirmationCode,
    );
  }

  //todo ask about remove this endpoint
  // @ApiOperation({ summary: 'Validate jwt token' })
  // @ApiBearerAuth()
  // @UseGuards(JwtAuthenticationGuard)
  // @Get('validate')
  // validateToken(@Req() request) {
  //   return { statusCode: 200, message: 'Token is valid' };
  // }
}
