# version of docker-compose
version: '3.9'

services:
  app:
    restart: on-failure
    build:
      context: .
    env_file: ./.env
    environment:
      - ENV_NAME=dev

    ports:
      - '3000:3000'