name: Pull request validate

on:
  pull_request:
    types: [opened, reopened]

jobs:

  lint_test_and_build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          node-version: 16
      - name: '🚀 Install pnpm'
        run: npm add -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint application code
        run: pnpm lint
      - name: Run application tests
        run: pnpm test
      - name: Build application
        run: pnpm run-script build